#!/bin/bash

seriesName='""'
enableNobbles=0
dontMoveDir=0
while getopts s:hon o
do case "$o" in
		s)
			seriesName="$OPTARG"
		;;
		o)	
			enableNobbles=1
		;;
		n)
			dontMoveDir=1
		;;
		h|\?)	
			echo -e "\n    autoname [-s 'Series Name'] [-on] filename\n"
			echo -e "\t -s to specify the TV Series manually"
			echo -e "\t -n to only rename the file, not move its directory"
			echo -e "\t -o to enable manual tweaks (overrides) from config.php\n" 
			exit 1
		;;
	esac
done

# Reset $@
shift $(($OPTIND-1))

#Resolve the current path of the symlink
# if the script has been symlinked into
# /usr/bin
SCRIPT_PATH="$0";
[[ -h "${SCRIPT_PATH}" ]] && SCRIPT_PATH=`readlink "${SCRIPT_PATH}"`
SCRIPT_PATH=`dirname "${SCRIPT_PATH}"`;

for var in "$@"; do
	php "${SCRIPT_PATH}"/Version2.php "${seriesName}" ${enableNobbles} ${dontMoveDir} "${var}"
done
