#!/bin/bash

seriesName=""
takeTVDBSeriesName=""
enableNobbles=""
dontMoveDir=""
enableOverwrites=""
seriesNumber=""
episodeNumber=""
mvinteractive=""
debugMode=""
targetDir=""
maskOverride=""
doCopy=""

while getopts s:S:e:t:m:acdhionf o
do case "$o" in
		c)	doCopy="-c" ;;
		d)	debugMode="-d"	;;
		a)	takeTVDBSeriesName="-a"  ;;
		s)	seriesName="${OPTARG}"	;;
		S)	seriesNumber="${OPTARG}"	;;
		e)	episodeNumber="${OPTARG}"	;;
		t)	targetDir="${OPTARG}"	;;
		m)	maskOverride="${OPTARG}"	;;
		o)	enableNobbles="-o"	;;
		n)	dontMoveDir="-n"	;;
		f)	enableOverwrites="-f"	;;
		i)	mvinteractive="-i"	;;
		h|\?)
			echo -e "\n    autoname [-s 'Series Name'] [-S 'Series #'] [-e 'Episode #'] [-t '/tmp/'] [-m '<SeriesNo>x<EpisodeNo>'] [-cdifno] filename\n"
			echo -e "\t -c to use cp instead of mv"
			echo -e "\t -d to dump the retrieved XML to stderr (for debugging)"
			echo -e "\t -a to automatically use the name of the series from TVDB"
			echo -e "\t -s to specify the TV Series name manually"
			echo -e "\t -S to specify the Series number manually"
			echo -e "\t -e to specify the Episode number manually"
			echo -e "\t -t to specify the Base target directory manually"
			echo -e "\t -m to specify the Rename filename mask manually"
			echo -e "\t -i to prompt before overwriting files (mv -i)"
			echo -e "\t -f to enable file overwrites (mv -f)"
			echo -e "\t -n to only rename the file, not move its directory"
			echo -e "\t -o to enable manual tweaks (overrides) from config.php\n"
			echo -e "If -o is specified, the -sSe options are applied prior to looking up overrides in config.php"
			echo -e "Rename filename mask replacement tokens are: <SeriesName>, <SeriesNo>, <EpisodeNo>, <EpisodeName>; file extensions are appended automatically."
			exit 1
		;;
	esac
done

# Reset $@
shift $(($OPTIND-1))

#Resolve the current path of the symlink
# if the script has been symlinked into
# /usr/bin
SCRIPT_PATH="$0";
[[ -h "${SCRIPT_PATH}" ]] && SCRIPT_PATH=`readlink "${SCRIPT_PATH}"`
SCRIPT_PATH=`dirname "${SCRIPT_PATH}"`;

for var in "$@"; do
	php "${SCRIPT_PATH}"/Version2.php -s "${seriesName}" -S "${seriesNumber}" -e "${episodeNumber}" -t "${targetDir}" \
		-m "${maskOverride}" ${takeTVDBSeriesName} ${debugMode} ${doCopy} ${enableOverwrites} ${enableNobbles} ${dontMoveDir} ${mvinteractive} "${var}"
done
